name: Middldeman site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@master
      with:
        ruby-version: '2.7'
    - name: Build the site with MIddleman
      run: gem install bundler; cd docs; bundle install; bundle exec middleman build
    - name: Puhlish site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
